import productImage1 from "../assets/store/product_1.png";
import productImage2 from "../assets/store/product_2.png";
import productImage3 from "../assets/store/product_3.png";
import productImage4 from "../assets/store/product_4.png";
import productImage5 from "../assets/store/product_5.png";
import productImage6 from "../assets/store/product_6.png";

export const products = [
  {
    id: 1,
    name: "Basic Slim Fit T-Shirt",
    price: 200000,
    category: "Cotton T-shirt",
    size: "S, M, L, XL",
    description: "Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.",
    image: productImage1,
    availability: "Available",
    gender: "Men",
    colors: ["Red", "Blue"],
    collections: "Summer",
    tags: ["Casual"],
    rating: "4 Stars",
  },
  {
    id: 2,
    name: "Basic Heavy Weight T-shirt",
    price: 200000,
    category: "Crewneck T-shirt",
    size: "S, M, L, XL, 2XL",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: productImage2,
    availability: "Out of Stock",
    gender: "Women",
    colors: ["Green", "Blue"],
    collections: "Spring",
    tags: ["Formal"],
    rating: "5 Stars",
  },
  {
    id: 3,
    name: "Full Sleeve Zipper",
    price: 200000,
    category: "Cotton Shirt",
    size: "S, M, XL, 2XL",
    description: "Sed cursus ante dapibus diam. Sed nisi.",
    image: productImage3,
    availability: "Available",
    gender: "Men",
    colors: ["Red"],
    collections: "Winter",
    tags: ["Sports"],
    rating: "3 Stars",
  },
  {
    id: 4,
    name: "Full Sleeve Zipper",
    price: 200000,
    category: "Cotton T-shirt",
    size: "S, L, XL, 2XL",
    description: "Duis sagittis ipsum. Praesent mauris.",
    image: productImage4,
    availability: "Available",
    gender: "Women",
    colors: ["Blue"],
    collections: "Winter",
    tags: ["Casual", "Formal"],
    rating: "4 Stars",
  },
  {
    id: 5,
    name: "Full Sleeve Zipper",
    price: 200000,
    category: "Cotton T-shirt",
    size: "S, M, L, 2XL",
    description: "Maecenas malesuada. Praesent congue erat at massa.",
    image: productImage5,
    availability: "Out of Stock",
    gender: "Kids",
    colors: ["Green"],
    collections: "Spring",
    tags: ["Sports"],
    rating: "2 Stars",
  },
  {
    id: 6,
    name: "Full Sleeve Zipper",
    price: 200000,
    category: "Cotton T-shirt",
    size: "S, M, L, XL, 2XL",
    description: "Etiam feugiat lorem non metus.",
    image: productImage6,
    availability: "Available",
    gender: "Men",
    colors: ["Red", "Blue", "Green"],
    collections: "Summer",
    tags: ["Casual", "Sports"],
    rating: "5 Stars",
  },
];
